# Generated by Django 3.2.15 on 2022-10-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devian', '0005_alter_question_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
