# Generated by Django 3.2.15 on 2022-10-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_rank'),
        ('devian', '0006_auto_20221005_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_category', models.CharField(max_length=150)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('report_for', models.CharField(choices=[('Question', 'Question Reports'), ('Answer', 'Answer Reports')], max_length=150)),
                ('report_id', models.CharField(max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_by_profile', to='core.profile')),
            ],
        ),
    ]
